# NASA PDF URLs to download
pdf_urls:
  # NASA Official Documents
  - name: "Mars Science Laboratory Telecommunications Design"
    url: "https://ntrs.nasa.gov/api/citations/20100023249/downloads/20100023249.pdf"
  - name: "Mars Exploration Rover Mission Status"
    url: "https://ntrs.nasa.gov/api/citations/20040082772/downloads/20040082772.pdf"
  - name: "Astrobiological Exploration of Mars"
    url: "https://ntrs.nasa.gov/api/citations/19940023533/downloads/94n23533.pdf"
  - name: "NASA Analog Missions and Field Tests"
    url: "https://www.nasa.gov/wp-content/uploads/2015/06/541196main_analogfactsheet.pdf"
  - name: "Life Into Space Volume 1"
    url: "https://www.nasa.gov/wp-content/uploads/2015/03/life_into_space_vol1.pdf"
  - name: "The Human Body in Space"
    url: "https://www.nasa.gov/wp-content/uploads/2021/02/bodyinspace_revised_forweb-2022-updated.pdf"
  - name: "Vision for Space Exploration"
    url: "https://www.nasa.gov/wp-content/uploads/2023/01/55583main_vision_space_exploration2.pdf"
  - name: "NASA Technical Report 1966-28277"
    url: "https://ntrs.nasa.gov/api/citations/19660028277/downloads/19660028277.pdf"
  - name: "NASA Technical Report 1975-18877"
    url: "https://ntrs.nasa.gov/api/citations/19750018877/downloads/19750018877.pdf"
  - name: "NASA Technical Report 1991-23710"
    url: "https://ntrs.nasa.gov/api/citations/19910023710/downloads/19910023710.pdf"
  - name: "NASA Technical Report 1987-16581"
    url: "https://ntrs.nasa.gov/api/citations/19870016581/downloads/19870016581.pdf"
  - name: "NASA Technical Report 2014-02636"
    url: "https://ntrs.nasa.gov/api/citations/20140002636/downloads/20140002636.pdf"
  - name: "NASA Technical Report 1994-28561"
    url: "https://ntrs.nasa.gov/api/citations/19940028561/downloads/19940028561.pdf"
  - name: "NASA Technical Report 1975-16569"
    url: "https://ntrs.nasa.gov/api/citations/19750016569/downloads/19750016569.pdf"
  - name: "NASA Technical Report 1994-31933"
    url: "https://ntrs.nasa.gov/api/citations/19940031933/downloads/19940031933.pdf"
  - name: "NASA Technical Report 2022-07536"
    url: "https://ntrs.nasa.gov/api/citations/20220007536/downloads/REU_2022_taiyou_kihon_kyouiku_Happyou.keynote.pdf"
  - name: "NASA Technical Report 2016-01564"
    url: "https://ntrs.nasa.gov/api/citations/20160001564/downloads/20160001564.pdf"

  # Space Science Books
  - name: "From Cosmos to Chaos - Peter Coles"
    url: "https://download.books.ms/main/15000/b0fea4e3b552e3720b7ad610d6e7b19b/Peter%20Coles%20-%20From%20cosmos%20to%20chaos_%20the%20science%20of%20unpredictability-Oxford%20University%20Press%20%282006%29.pdf"
  - name: "Cosmos - Carl Sagan"
    url: "https://download.books.ms/main/224000/494af965c8f206d07acecfa10ad213c0/Carl%20Sagan%20-%20Cosmos-Ballantine%20Books%20%281985%29.pdf"
  - name: "Death by Black Hole - Neil deGrasse Tyson"
    url: "https://download.books.ms/main/460000/e6f8c1321e621c403cb3c00f4041facc/Neil%20deGrasse%20Tyson%20-%20Death%20by%20Black%20Hole_%20And%20Other%20Cosmic%20Quandaries-W.%20W.%20Norton%20%26%20Company%20%282007%29.pdf"
  - name: "Astrophysics for Young People in a Hurry - Neil deGrasse Tyson"
    url: "https://download.books.ms/main/4475000/ed3ed34ae4ad67b04a30542cd563a5b2/Neil%20deGrasse%20Tyson%20-%20Astrophysics%20for%20Young%20People%20in%20a%20Hurry-W.%20W.%20Norton%20%26%20Company%20%282019%29.pdf"
  - name: "Astrophysics for People in a Hurry - Neil deGrasse Tyson"
    url: "https://download.books.ms/main/2067000/44c0cf923d8adf1b619fa176048c5e25/Neil%20deGrasse%20Tyson%20-%20Astrophysics%20for%20People%20in%20a%20Hurry-W.%20W.%20Norton%20%26%20Co%20%282017%29.pdf"
  - name: "Astronomy for Beginners - Fiona Hudson"
    url: "https://download.books.ms/main/2553000/457df0123c92356171e6d1c85217e1d4/%28All%20about%20space%20bookazine%20series%29%20Fiona%20Hudson%20%28editor%29%20-%20Astronomy%20for%20beginners%20_%20all%20you%20need%20to%20know%20to%20get%20started%20in%20astronomy%20%282016%29.pdf"
  - name: "Dimensions - Jacques Vallee"
    url: "https://download.books.ms/main/568000/1a73acbbd897bfcd883c4fa6032c21b4/Jacques%20Vallee%20-%20Dimensions%20%28Mysteries%20of%20the%20Universe%20Series%29-Souvenir%20Press%20Ltd%20%281996%29.pdf"
  - name: "The Mysteries of the Universe - Franklyn M. Branley"
    url: "https://download.books.ms/main/613000/ec791631b56e91f6f9faa0dde73c93a5/Franklyn%20M.%20Branley%20-%20The%20Mysteries%20of%20the%20Universe_%202%20%28Mysteries%20of%20the%20Universe%20Series%29-Dutton%20Juvenile%20%281984%29.pdf"

  # Physics and Cosmology Books
  - name: "The Elegant Universe - Brian Greene"
    url: "https://download.books.ms/main/223000/bdf12e54c00f58ac6a95859983561159/Brian%20Greene%20-%20The%20Elegant%20Universe-W.%20W.%20Norton%20%26%20Company%20%282003%29.pdf"
  - name: "A Brief History of Time - Stephen Hawking"
    url: "https://download.books.ms/main/16000/44f20116d682817619c770fcdbf66123/Stephen%20W.%20Hawking%2C%20Ron%20Miller%2C%20Carl%20Sagan%20-%20A%20Brief%20History%20of%20Time_%20From%20the%20Big%20Bang%20to%20Black%20Holes%20-Bantam%20%281988%29.pdf"
  - name: "Einsteins Traum - Stephen Hawking"
    url: "https://download.books.ms/main/16000/09330f7151f6f34b2c5b879d5cdeacb5/Stephen%20W.%20Hawking%20-%20Einsteins%20Traum-Rowohlt%20Verlag%2C%20GmbH%20%281994%29.pdf"
  - name: "The Theory of Everything - Stephen Hawking"
    url: "https://download.books.ms/main/16000/be164417a5b65a0fe68e1e9a59f3f833/Stephen%20W%20Hawking%20-%20The%20theory%20of%20everything-Phoenix%20Books%20%282006%29.pdf"
  - name: "The Nature of Space and Time - Stephen Hawking & Roger Penrose"
    url: "https://download.books.ms/main/304000/2500c434af9ef3314ad33f9caef2e815/Stephen%20W.%20Hawking%2C%20Roger%20Penrose%20-%20The%20Nature%20of%20Space%20and%20Time-Princeton%20University%20Press%20%281996%29.pdf"
  - name: "Hawking on the Big Bang and Black Holes - Stephen Hawking"
    url: "https://download.books.ms/main/460000/e7a059739e6c8fdfaa678ae188c12b71/Stephen%20W.%20Hawking%20-%20Hawking%20on%20the%20Big%20Bang%20and%20Black%20Holes%20%28Advanced%20Series%20in%20Astrophysics%20and%20Cosmology%2C%20Vol%208%29-World%20Scientific%20Publishing%20Company%20%281993%29.pdf"
  - name: "Gravitation - Misner, Thorne & Wheeler"
    url: "https://download.books.ms/main/725000/0aeabe2b15f924116f7c5a734f3f94fc/Charles%20W.%20Misner%2C%20Kip%20S.%20Thorne%2C%20John%20Archibald%20Wheeler%2C%20John%20Wheeler%2C%20Kip%20Thorne%20-%20Gravitation%20%28Physics%20Series%29%20%20-W.%20H.%20Freeman%20%281973%29.pdf"
  - name: "Applications of Classical Physics - Blandford & Thorne"
    url: "https://download.books.ms/main/915000/dff648b32266d6fd10c4e7905635cf7a/Roger%20Blanford%2C%20Kip%20Thorne%20-%20Applications%20of%20Classical%20Physics%20%28web%20draft%20april%202013%29%20%282013%29.pdf"
  - name: "The Science of Interstellar - Kip Thorne & Christopher Nolan"
    url: "https://download.books.ms/main/1295000/082b5e429865fc1701163c2c2f923c23/Kip%20Thorne%2C%20Christopher%20Nolan%20-%20The%20Science%20of%20Interstellar-Norton%2C%20W.%20W.%20%26%20Company%2C%20Inc.%20%282014%29.pdf"
  - name: "Modern Classical Physics - Blandford & Thorne"
    url: "https://download.books.ms/main/2359000/8fde47f8ae45fcbcf828487d1921b954/Blandford%2C%20Roger%20D._%20Thorne%2C%20Kip%20S%20-%20Modern%20classical%20physics_%20optics%2C%20fluids%2C%20plasmas%2C%20elasticity%2C%20relativity%2C%20and%20statistical%20physics-Princeton%20University%20Press%20%282017%29.pdf"

# Directory configurations
directories:
  pdf_save_dir: "pdfs"
  vector_db_dir: "chroma_db" 